#include "dictionary/core_dict.h"

#include <algorithm>
#include <limits>
#include <string>
#include <vector>

// v0.8: Only closed class entries (function words)
// Open class words (nouns, verbs, adjectives, adverbs) are handled by:
// - Analysis engine (conjugation generation)
// - L2 dictionary (core.dic)
#include "dictionary/entries/auxiliaries.h"
#include "dictionary/entries/compound_particles.h"
#include "dictionary/entries/conjunctions.h"
#include "dictionary/entries/determiners.h"
#include "dictionary/entries/formal_nouns.h"
#include "dictionary/entries/particles.h"
#include "dictionary/entries/pronouns.h"

namespace suzume::dictionary {

namespace {

// NOTE: v0.8 - Removed expandVerbEntry()
// Conjugated forms are now generated by the analysis engine at runtime,
// not pre-generated in the dictionary.

// NOTE: v0.8 - Removed expandAdjectiveEntry()
// Conjugated forms are now generated by the analysis engine at runtime,
// not pre-generated in the dictionary.

}  // namespace

CoreDictionary::CoreDictionary() { initializeEntries(); }

void CoreDictionary::initializeEntries() {
  // ==========================================================================
  // v0.8: Layer 1 only - Closed class entries (function words)
  // ==========================================================================
  // These are grammatically fixed sets with known upper bounds.
  // They rarely change and are tied to language structure.
  //
  // Open class words (nouns, verbs, adjectives, adverbs) are:
  // - Generated by analysis engine (verb/adjective conjugation)
  // - Loaded from L2 dictionary (core.dic) if available
  auto particles = entries::getParticleEntries();
  auto compound_particles = entries::getCompoundParticleEntries();
  auto auxiliaries = entries::getAuxiliaryEntries();
  auto conjunctions = entries::getConjunctionEntries();
  auto determiners = entries::getDeterminerEntries();
  auto pronouns = entries::getPronounEntries();
  auto formal_nouns = entries::getFormalNounEntries();

  // Reserve space
  entries_.reserve(particles.size() + compound_particles.size() +
                   auxiliaries.size() + conjunctions.size() +
                   determiners.size() + pronouns.size() + formal_nouns.size());

  // Collect entries (trie built after sorting)
  auto addEntries = [this](const std::vector<DictionaryEntry>& source) {
    for (const auto& entry : source) {
      entries_.push_back(entry);
    }
  };

  addEntries(particles);
  addEntries(compound_particles);
  addEntries(auxiliaries);
  addEntries(conjunctions);
  addEntries(determiners);
  addEntries(pronouns);
  addEntries(formal_nouns);

  // Sort entries by surface for Double-Array compatibility
  // Use stable_sort to preserve relative order of entries with same surface
  std::stable_sort(entries_.begin(), entries_.end(),
                   [](const DictionaryEntry& lhs, const DictionaryEntry& rhs) {
                     return lhs.surface < rhs.surface;
                   });

  // Build Double-Array trie
  buildTrie();
}

void CoreDictionary::buildTrie() {
  if (entries_.empty()) {
    return;
  }

  // Build unique keys with first occurrence index
  std::vector<std::string> keys;
  std::vector<int32_t> values;

  // Entries are sorted by surface, so extract unique keys
  // Store the first index for each surface - lookup() will collect all
  // consecutive entries with the same surface
  std::string prev_surface;
  size_t first_idx = 0;

  for (size_t idx = 0; idx < entries_.size(); ++idx) {
    const auto& entry = entries_[idx];
    if (entry.surface != prev_surface) {
      // New surface - save previous first if exists
      if (!prev_surface.empty()) {
        keys.push_back(prev_surface);
        values.push_back(static_cast<int32_t>(first_idx));
      }
      // Start tracking new surface
      prev_surface = entry.surface;
      first_idx = idx;
    }
    // For same surface, first_idx stays unchanged (first occurrence)
  }
  // Don't forget the last surface
  if (!prev_surface.empty()) {
    keys.push_back(prev_surface);
    values.push_back(static_cast<int32_t>(first_idx));
  }

  // Build the Double-Array trie
  trie_.build(keys, values);
}

namespace {

/**
 * @brief Count UTF-8 characters in a byte range
 */
size_t countUtf8Chars(std::string_view text, size_t start_byte,
                      size_t byte_length) {
  size_t char_count = 0;
  size_t end_byte = start_byte + byte_length;

  for (size_t pos = start_byte; pos < end_byte && pos < text.size();) {
    auto byte = static_cast<uint8_t>(text[pos]);
    if ((byte & 0xC0) != 0x80) {
      ++char_count;
    }
    ++pos;
  }

  return char_count;
}

}  // namespace

std::vector<LookupResult> CoreDictionary::lookup(std::string_view text,
                                                 size_t start_pos) const {
  std::vector<LookupResult> results;

  if (entries_.empty() || start_pos >= text.size()) {
    return results;
  }

  // Use Double-Array common prefix search
  auto trie_results = trie_.commonPrefixSearch(text, start_pos);

  for (const auto& tres : trie_results) {
    if (tres.value < 0 || static_cast<size_t>(tres.value) >= entries_.size()) {
      continue;
    }

    size_t first_idx = static_cast<size_t>(tres.value);
    const std::string& matched_surface = entries_[first_idx].surface;

    // Collect all entries with the same surface (consecutive in sorted array)
    for (size_t idx = first_idx; idx < entries_.size(); ++idx) {
      if (entries_[idx].surface != matched_surface) {
        break;
      }

      LookupResult result{};
      result.entry_id = static_cast<uint32_t>(idx);
      // Convert byte length to character count
      result.length = countUtf8Chars(text, start_pos, tres.length);
      result.entry = &entries_[idx];
      results.push_back(result);
    }
  }

  return results;
}

const DictionaryEntry* CoreDictionary::getEntry(uint32_t idx) const {
  if (idx < entries_.size()) {
    return &entries_[idx];
  }
  return nullptr;
}

}  // namespace dictionary
