#include "dictionary/core_dict.h"

#include <string>
#include <string_view>
#include <vector>

#include "dictionary/dictionary_lookup.h"

// Layer 1 is the finite built-in grammar inventory: function words plus
// grammar-licensed determiners, pronouns, formal nouns, and interjections.
// Productive open-class nouns, verbs, adjectives, and adverbs are handled by:
// - Analysis engine (conjugation generation)
// - L2 dictionary (core.dic)
#ifdef __EMSCRIPTEN__
#include "dictionary/entries/packed_core_entries.h"
#else
#include "dictionary/entries/auxiliaries.h"
#include "dictionary/entries/compound_particles.h"
#include "dictionary/entries/conjunctions.h"
#include "dictionary/entries/determiners.h"
#include "dictionary/entries/formal_nouns.h"
#include "dictionary/entries/interjections.h"
#include "dictionary/entries/particles.h"
#include "dictionary/entries/pronouns.h"
#endif

namespace suzume::dictionary {

namespace {

#ifndef __EMSCRIPTEN__
void stableSortEntrySpecs(std::vector<entries::EntrySpec>& entry_specs) {
  std::vector<entries::EntrySpec> buffer(entry_specs.size());
  for (size_t width = 1; width < entry_specs.size(); width *= 2) {
    for (size_t left = 0; left < entry_specs.size(); left += width * 2) {
      const size_t middle = left + width < entry_specs.size() ? left + width : entry_specs.size();
      const size_t right = middle + width < entry_specs.size() ? middle + width : entry_specs.size();
      size_t lhs = left;
      size_t rhs = middle;
      size_t output = left;
      while (lhs < middle && rhs < right) {
        if (std::string_view(entry_specs[rhs].surface) < std::string_view(entry_specs[lhs].surface)) {
          buffer[output++] = entry_specs[rhs++];
        } else {
          buffer[output++] = entry_specs[lhs++];
        }
      }
      while (lhs < middle) {
        buffer[output++] = entry_specs[lhs++];
      }
      while (rhs < right) {
        buffer[output++] = entry_specs[rhs++];
      }
    }
    entry_specs.swap(buffer);
  }
}
#endif

}  // namespace

CoreDictionary::CoreDictionary() {
  initializeEntries();
}

void CoreDictionary::initializeEntries() {
  // ==========================================================================
  // Layer 1 - finite built-in grammar inventory
  // ==========================================================================
  // These are grammatically bounded sets with known upper limits. Alongside
  // function words, this includes finite lexical sets whose grammatical role
  // is required before an external dictionary is loaded.
  //
  // Open class words (nouns, verbs, adjectives, adverbs) are:
  // - Generated by analysis engine (verb/adjective conjugation)
  // - Loaded from L2 dictionary (core.dic) if available
#ifdef __EMSCRIPTEN__
  const auto packed_entries = entries::getPackedCoreEntries();
  const char* string_data = reinterpret_cast<const char*>(packed_entries.stringData());
  entries_.reserve(packed_entries.size());
  for (const auto& entry : packed_entries) {
    entries_.push_back({string_data + entry.surface_offset, static_cast<core::PartOfSpeech>(entry.pos),
                        static_cast<core::ExtendedPOS>(entry.extended_pos), string_data + entry.lemma_offset});
  }
#else
  // Registration order matters for duplicate surfaces; packed_core_entries_sources.cmake mirrors it.
  const entries::EntrySpecRange sources[] = {
      entries::getParticleEntries(),    entries::getCompoundParticleEntries(), entries::getAuxiliaryEntries(),
      entries::getConjunctionEntries(), entries::getDeterminerEntries(),       entries::getPronounEntries(),
      entries::getFormalNounEntries(),  entries::getInterjectionEntries(),
  };
  size_t entry_count = 0;
  for (const auto& source : sources) {
    entry_count += source.size();
  }

  // Sort the trivial source records before constructing owned strings. This
  // keeps all materialization in one loop and makes the stable-sort
  // instantiation much smaller than sorting DictionaryEntry objects.
  std::vector<entries::EntrySpec> entry_specs;
  entry_specs.reserve(entry_count);
  for (const auto& source : sources) {
    entry_specs.insert(entry_specs.end(), source.begin(), source.end());
  }

  // Sort entries by surface for Double-Array compatibility while preserving
  // the registration order of duplicate surfaces.
  stableSortEntrySpecs(entry_specs);

  entries_.reserve(entry_count);
  for (const auto& entry : entry_specs) {
    entries_.push_back({entry.surface, entry.pos, entry.extended_pos, entry.lemma});
  }
#endif

  // Build Double-Array trie
  buildTrie();
}

void CoreDictionary::buildTrie() {
  if (entries_.empty()) {
    return;
  }

  // Build unique keys with first occurrence index. Entries are already sorted,
  // so a comparison with the previous item is sufficient.
  std::vector<std::string> keys;
  std::vector<uint32_t> values;
  keys.reserve(entries_.size());
  values.reserve(entries_.size());
  for (size_t idx = 0; idx < entries_.size(); ++idx) {
    if (idx == 0 || entries_[idx].surface != entries_[idx - 1].surface) {
      keys.push_back(entries_[idx].surface);
      values.push_back(static_cast<uint32_t>(idx));
    }
  }

  // Build the Double-Array trie
  trie_.build(keys, values);
}

std::vector<LookupResult> CoreDictionary::lookup(std::string_view text, size_t start_pos) const {
  return lookupByTrie(trie_, entries_, text, start_pos);
}

const DictionaryEntry* CoreDictionary::getEntry(uint32_t idx) const {
  return entryAt(entries_, idx);
}

const DictionaryEntry* CoreDictionary::lookupExact(std::string_view surface, core::PartOfSpeech pos) const {
  return lookupExactByTrie(trie_, entries_, surface, pos);
}

}  // namespace suzume::dictionary
