"""Facade for the focused merge post-processing passes."""

from . import (
    merge_postprocessor_affixes,
    merge_postprocessor_classical_adjectives,
    merge_postprocessor_classical_verbs,
    merge_postprocessor_common,
    merge_postprocessor_grammar,
    merge_postprocessor_spelling,
)

# Exports from merge_postprocessor_affixes.
_BOUND_ADJECTIVE_PREFIX = merge_postprocessor_affixes._BOUND_ADJECTIVE_PREFIX
_is_quantity_unit = merge_postprocessor_affixes._is_quantity_unit
_postprocess_bound_prefix_adjective = merge_postprocessor_affixes._postprocess_bound_prefix_adjective
_postprocess_bound_suffix_noun_cell = merge_postprocessor_affixes._postprocess_bound_suffix_noun_cell
_postprocess_bound_voiced_suffix = merge_postprocessor_affixes._postprocess_bound_voiced_suffix
_postprocess_distributive_quantity = merge_postprocessor_affixes._postprocess_distributive_quantity
_postprocess_nominal_zukeru = merge_postprocessor_affixes._postprocess_nominal_zukeru
_postprocess_search_unit_split = merge_postprocessor_affixes._postprocess_search_unit_split

# Exports from merge_postprocessor_classical_adjectives.
_KARI_CELL_POS = merge_postprocessor_classical_adjectives._KARI_CELL_POS
_KARI_CLASSICAL_PAST_CELLS = merge_postprocessor_classical_adjectives._KARI_CLASSICAL_PAST_CELLS
_KARI_CONTINUATIVE = merge_postprocessor_classical_adjectives._KARI_CONTINUATIVE
_KARI_MAX_TOKEN_RUN = merge_postprocessor_classical_adjectives._KARI_MAX_TOKEN_RUN
_KARI_PROBE_CELLS = merge_postprocessor_classical_adjectives._KARI_PROBE_CELLS
_KARI_TAILS = merge_postprocessor_classical_adjectives._KARI_TAILS
_KU_NOMINALIZER = merge_postprocessor_classical_adjectives._KU_NOMINALIZER
KARI_MIZENKEI_CELL = merge_postprocessor_classical_adjectives.KARI_MIZENKEI_CELL
_kari_cell_analysis = merge_postprocessor_classical_adjectives._kari_cell_analysis
_kari_probe_token = merge_postprocessor_classical_adjectives._kari_probe_token
_postprocess_adj_bungo = merge_postprocessor_classical_adjectives._postprocess_adj_bungo
_postprocess_adj_kari = merge_postprocessor_classical_adjectives._postprocess_adj_kari
_postprocess_ku_nominalization = merge_postprocessor_classical_adjectives._postprocess_ku_nominalization
classical_adjective_lemma = merge_postprocessor_classical_adjectives.classical_adjective_lemma

# Exports from merge_postprocessor_classical_verbs.
_CLASSICAL_CAUSATIVE_FORMS = merge_postprocessor_classical_verbs._CLASSICAL_CAUSATIVE_FORMS
_CLASSICAL_COPULA_BASE = merge_postprocessor_classical_verbs._CLASSICAL_COPULA_BASE
_CLASSICAL_COPULA_LEMMA = merge_postprocessor_classical_verbs._CLASSICAL_COPULA_LEMMA
_CLASSICAL_IRREALIS_AUX = merge_postprocessor_classical_verbs._CLASSICAL_IRREALIS_AUX
_CONCESSIVE_PARTICLES = merge_postprocessor_classical_verbs._CONCESSIVE_PARTICLES
_E_ROW_TO_U_ROW = merge_postprocessor_classical_verbs._E_ROW_TO_U_ROW
_HA_ROW_DETACHED_TAILS = merge_postprocessor_classical_verbs._HA_ROW_DETACHED_TAILS
_HA_ROW_FRAME_STEM = merge_postprocessor_classical_verbs._HA_ROW_FRAME_STEM
_HA_ROW_STEM_POS = merge_postprocessor_classical_verbs._HA_ROW_STEM_POS
_HA_ROW_TAILS = merge_postprocessor_classical_verbs._HA_ROW_TAILS
_HIRAGANA_TAIL = merge_postprocessor_classical_verbs._HIRAGANA_TAIL
_KAKARI_PARTICLES = merge_postprocessor_classical_verbs._KAKARI_PARTICLES
_NIDAN_AUXILIARY_HOMOGRAPHS = merge_postprocessor_classical_verbs._NIDAN_AUXILIARY_HOMOGRAPHS
_NIDAN_CELL = merge_postprocessor_classical_verbs._NIDAN_CELL
_NIDAN_INFLECTED_STEM_FORMS = merge_postprocessor_classical_verbs._NIDAN_INFLECTED_STEM_FORMS
_NIDAN_TERMINAL_ROWS = merge_postprocessor_classical_verbs._NIDAN_TERMINAL_ROWS
_PAST_CONJECTURAL = merge_postprocessor_classical_verbs._PAST_CONJECTURAL
_PAST_CONJECTURAL_HOST_POS = merge_postprocessor_classical_verbs._PAST_CONJECTURAL_HOST_POS
_PAST_KI = merge_postprocessor_classical_verbs._PAST_KI
_SINGLE_KANJI = merge_postprocessor_classical_verbs._SINGLE_KANJI
_TOMO_CONCESSIVE_AUXILIARIES = merge_postprocessor_classical_verbs._TOMO_CONCESSIVE_AUXILIARIES
NIDAN_TERMINAL_KANA = merge_postprocessor_classical_verbs.NIDAN_TERMINAL_KANA
_bare_kanji_vowel_stem_lemma = merge_postprocessor_classical_verbs._bare_kanji_vowel_stem_lemma
_ha_row_cell_auxiliary = merge_postprocessor_classical_verbs._ha_row_cell_auxiliary
_ha_row_fabricated_ichidan = merge_postprocessor_classical_verbs._ha_row_fabricated_ichidan
_modern_kana_word = merge_postprocessor_classical_verbs._modern_kana_word
_nidan_cell_match = merge_postprocessor_classical_verbs._nidan_cell_match
_nidan_terminal_lemma = merge_postprocessor_classical_verbs._nidan_terminal_lemma
_postprocess_classical_kemu = merge_postprocessor_classical_verbs._postprocess_classical_kemu
_postprocess_classical_ki = merge_postprocessor_classical_verbs._postprocess_classical_ki
_postprocess_classical_mu = merge_postprocessor_classical_verbs._postprocess_classical_mu
_postprocess_classical_shimu = merge_postprocessor_classical_verbs._postprocess_classical_shimu
_postprocess_ha_row_godan = merge_postprocessor_classical_verbs._postprocess_ha_row_godan
_postprocess_historical_kana_word = merge_postprocessor_classical_verbs._postprocess_historical_kana_word
_postprocess_izenkei_concessive = merge_postprocessor_classical_verbs._postprocess_izenkei_concessive
_postprocess_kakari_pronoun_split = merge_postprocessor_classical_verbs._postprocess_kakari_pronoun_split
_postprocess_nidan_cell = merge_postprocessor_classical_verbs._postprocess_nidan_cell
_postprocess_nominal_classical_copula = merge_postprocessor_classical_verbs._postprocess_nominal_classical_copula
_postprocess_nominal_copula_naru = merge_postprocessor_classical_verbs._postprocess_nominal_copula_naru
_postprocess_tomo_particle = merge_postprocessor_classical_verbs._postprocess_tomo_particle
_promote_bare_kanji_host = merge_postprocessor_classical_verbs._promote_bare_kanji_host
_reads_as_pronoun = merge_postprocessor_classical_verbs._reads_as_pronoun
_retag_suffix_without_host = merge_postprocessor_classical_verbs._retag_suffix_without_host
nidan_cell = merge_postprocessor_classical_verbs.nidan_cell

# Exports from merge_postprocessor_common.
_A_ROW_TO_U_ROW = merge_postprocessor_common._A_ROW_TO_U_ROW
_CONTINUATIVE_PROBE_AUXILIARY = merge_postprocessor_common._CONTINUATIVE_PROBE_AUXILIARY
_continuative_verb_tokens = merge_postprocessor_common._continuative_verb_tokens
_is_single_verb = merge_postprocessor_common._is_single_verb
_plain = merge_postprocessor_common._plain
_probe_continuative = merge_postprocessor_common._probe_continuative
reads_as_continuative = merge_postprocessor_common.reads_as_continuative

# Exports from merge_postprocessor_grammar.
_CLOSED_CLASS_BEFORE_PREFIX = merge_postprocessor_grammar._CLOSED_CLASS_BEFORE_PREFIX
_CONJUNCTIVE_TE = merge_postprocessor_grammar._CONJUNCTIVE_TE
_CONTINUATIVE_CELL = merge_postprocessor_grammar._CONTINUATIVE_CELL
_DECOMPOSABLE_ADVERB_TAILS = merge_postprocessor_grammar._DECOMPOSABLE_ADVERB_TAILS
_DERIVATIONAL_NOMINAL_SUFFIXES = merge_postprocessor_grammar._DERIVATIONAL_NOMINAL_SUFFIXES
_GAMASHII_TAILS = merge_postprocessor_grammar._GAMASHII_TAILS
_HONORIFIC_PREFIXES = merge_postprocessor_grammar._HONORIFIC_PREFIXES
_ICHIDAN_CONJ_TYPE = merge_postprocessor_grammar._ICHIDAN_CONJ_TYPE
_IMPERATIVE_YO = merge_postprocessor_grammar._IMPERATIVE_YO
_IMPERATIVE_YO_CELL = merge_postprocessor_grammar._IMPERATIVE_YO_CELL
_INTERROGATIVE_HEADS = merge_postprocessor_grammar._INTERROGATIVE_HEADS
_PROGRESSIVE_LEMMAS = merge_postprocessor_grammar._PROGRESSIVE_LEMMAS
_decomposed_adverb_head = merge_postprocessor_grammar._decomposed_adverb_head
_heads_property_nominal = merge_postprocessor_grammar._heads_property_nominal
_postprocess_atode = merge_postprocessor_grammar._postprocess_atode
_postprocess_decomposable_adverb = merge_postprocessor_grammar._postprocess_decomposable_adverb
_postprocess_demo_copula = merge_postprocessor_grammar._postprocess_demo_copula
_postprocess_derivational_nominal_suffix = merge_postprocessor_grammar._postprocess_derivational_nominal_suffix
_postprocess_epenthetic_sa = merge_postprocessor_grammar._postprocess_epenthetic_sa
_postprocess_filler_split = merge_postprocessor_grammar._postprocess_filler_split
_postprocess_gamashii = merge_postprocessor_grammar._postprocess_gamashii
_postprocess_honorific_split = merge_postprocessor_grammar._postprocess_honorific_split
_postprocess_ichidan_imperative_yo = merge_postprocessor_grammar._postprocess_ichidan_imperative_yo
_postprocess_kamo = merge_postprocessor_grammar._postprocess_kamo
_postprocess_kuruwa = merge_postprocessor_grammar._postprocess_kuruwa
_postprocess_nde_split = merge_postprocessor_grammar._postprocess_nde_split
_postprocess_nominal_before_conjunctive_te = merge_postprocessor_grammar._postprocess_nominal_before_conjunctive_te
_postprocess_noni = merge_postprocessor_grammar._postprocess_noni
_postprocess_prefix_split = merge_postprocessor_grammar._postprocess_prefix_split
_postprocess_totomoni = merge_postprocessor_grammar._postprocess_totomoni
_postprocess_word_internal_honorific_prefix = merge_postprocessor_grammar._postprocess_word_internal_honorific_prefix

# Exports from merge_postprocessor_spelling.
_ASCII_WORD_JOINERS = merge_postprocessor_spelling._ASCII_WORD_JOINERS
_CONTINUATIVE_FOLLOWERS = merge_postprocessor_spelling._CONTINUATIVE_FOLLOWERS
_EUPHONIC_CONTINUATIVE = merge_postprocessor_spelling._EUPHONIC_CONTINUATIVE
_EUPHONIC_SUFFIX_HEADS = merge_postprocessor_spelling._EUPHONIC_SUFFIX_HEADS
_HYPOTHETICAL_CELL = merge_postprocessor_spelling._HYPOTHETICAL_CELL
_HYPOTHETICAL_PARTICLE = merge_postprocessor_spelling._HYPOTHETICAL_PARTICLE
_IDEOGRAPHIC_SEQUENCE = merge_postprocessor_spelling._IDEOGRAPHIC_SEQUENCE
_MORA_VOWEL = merge_postprocessor_spelling._MORA_VOWEL
_NON_INITIAL_SMALL_KANA = merge_postprocessor_spelling._NON_INITIAL_SMALL_KANA
_O_ROW_KANA = merge_postprocessor_spelling._O_ROW_KANA
_STEM_ONLY_CONJ_FORMS = merge_postprocessor_spelling._STEM_ONLY_CONJ_FORMS
_VARIATION_SELECTORS = merge_postprocessor_spelling._VARIATION_SELECTORS
_is_licensed_attachment = merge_postprocessor_spelling._is_licensed_attachment
_is_productive_mimetic_stem = merge_postprocessor_spelling._is_productive_mimetic_stem
_is_split_reduplication = merge_postprocessor_spelling._is_split_reduplication
_opens_volitional_tto = merge_postprocessor_spelling._opens_volitional_tto
_postprocess_ascii_joiner_merge = merge_postprocessor_spelling._postprocess_ascii_joiner_merge
_postprocess_dialectal = merge_postprocessor_spelling._postprocess_dialectal
_postprocess_kanji_merge = merge_postprocessor_spelling._postprocess_kanji_merge
_postprocess_nickname_merge = merge_postprocessor_spelling._postprocess_nickname_merge
_postprocess_onomatopoeia_tto_merge = merge_postprocessor_spelling._postprocess_onomatopoeia_tto_merge
_postprocess_productive_mimetics = merge_postprocessor_spelling._postprocess_productive_mimetics
_postprocess_small_kana_head_merge = merge_postprocessor_spelling._postprocess_small_kana_head_merge
_postprocess_stranded_lengthening_vowel = merge_postprocessor_spelling._postprocess_stranded_lengthening_vowel
_postprocess_stranded_okurigana = merge_postprocessor_spelling._postprocess_stranded_okurigana
_postprocess_variation_selector_merge = merge_postprocessor_spelling._postprocess_variation_selector_merge
_spans_one_mimetic = merge_postprocessor_spelling._spans_one_mimetic


def apply_merge_postprocessors(result: list[dict], applied_rule: str | None) -> tuple[list[dict], str | None]:
    """Apply merge post-processors in the historical order."""
    result = _postprocess_kamo(result, applied_rule)
    result, applied_rule = _postprocess_totomoni(result, applied_rule)
    result, applied_rule = _postprocess_noni(result, applied_rule)
    result, applied_rule = _postprocess_atode(result, applied_rule)
    _postprocess_epenthetic_sa(result)
    result, applied_rule = _postprocess_honorific_split(result, applied_rule)
    result, applied_rule = _postprocess_prefix_split(result, applied_rule)
    result, applied_rule = _postprocess_nde_split(result, applied_rule)
    result, applied_rule = _postprocess_filler_split(result, applied_rule)
    result, applied_rule = _postprocess_kuruwa(result, applied_rule)
    result, applied_rule = _postprocess_demo_copula(result, applied_rule)
    result, applied_rule = _postprocess_gamashii(result, applied_rule)
    result, applied_rule = _postprocess_adj_bungo(result, applied_rule)
    result, applied_rule = _postprocess_adj_kari(result, applied_rule)
    result, applied_rule = _postprocess_ha_row_godan(result, applied_rule)
    result, applied_rule = _postprocess_nidan_cell(result, applied_rule)
    result, applied_rule = _postprocess_nominal_classical_copula(result, applied_rule)
    result, applied_rule = _postprocess_historical_kana_word(result, applied_rule)
    result, applied_rule = _postprocess_kakari_pronoun_split(result, applied_rule)
    result, applied_rule = _postprocess_classical_mu(result, applied_rule)
    result, applied_rule = _postprocess_ku_nominalization(result, applied_rule)
    result, applied_rule = _postprocess_classical_shimu(result, applied_rule)
    result, applied_rule = _postprocess_classical_kemu(result, applied_rule)
    result, applied_rule = _postprocess_classical_ki(result, applied_rule)
    result, applied_rule = _postprocess_nominal_copula_naru(result, applied_rule)
    result, applied_rule = _postprocess_nominal_before_conjunctive_te(result, applied_rule)
    result, applied_rule = _postprocess_derivational_nominal_suffix(result, applied_rule)
    result, applied_rule = _postprocess_ichidan_imperative_yo(result, applied_rule)
    result, applied_rule = _postprocess_stranded_okurigana(result, applied_rule)
    result, applied_rule = _postprocess_decomposable_adverb(result, applied_rule)
    result, applied_rule = _postprocess_bound_prefix_adjective(result, applied_rule)
    result, applied_rule = _postprocess_word_internal_honorific_prefix(result, applied_rule)
    result, applied_rule = _postprocess_variation_selector_merge(result, applied_rule)
    result, applied_rule = _postprocess_izenkei_concessive(result, applied_rule)
    result, applied_rule = _postprocess_tomo_particle(result, applied_rule)
    result, applied_rule = _postprocess_bound_voiced_suffix(result, applied_rule)
    result, applied_rule = _postprocess_bound_suffix_noun_cell(result, applied_rule)
    result, applied_rule = _postprocess_kanji_merge(result, applied_rule)
    result, applied_rule = _postprocess_nickname_merge(result, applied_rule)
    result, applied_rule = _postprocess_search_unit_split(result, applied_rule)
    result, applied_rule = _postprocess_onomatopoeia_tto_merge(result, applied_rule)
    result, applied_rule = _postprocess_productive_mimetics(result, applied_rule)
    result, applied_rule = _postprocess_distributive_quantity(result, applied_rule)
    result, applied_rule = _postprocess_nominal_zukeru(result, applied_rule)
    result, applied_rule = _postprocess_ascii_joiner_merge(result, applied_rule)
    result, applied_rule = _postprocess_small_kana_head_merge(result, applied_rule)
    result, applied_rule = _postprocess_stranded_lengthening_vowel(result, applied_rule)
    _postprocess_dialectal(result)
    return result, applied_rule
