#ifndef SUZUME_DICTIONARY_ENTRIES_HIRAGANA_VERBS_H_
#define SUZUME_DICTIONARY_ENTRIES_HIRAGANA_VERBS_H_

// =============================================================================
// Layer 1: Hiragana Verbs (ひらがな動詞) - Tokenization Critical
// =============================================================================
// High-frequency verbs written ENTIRELY in hiragana that start with
// particle-like characters (で, も, わ, etc.). Without these entries,
// the analyzer incorrectly splits them as particle + verb fragment.
//
// Examples of bugs this fixes:
//   できる → で + きる (wrong) → できる (correct)
//   もらう → も + らう (wrong) → もらう (correct)
//   わかる → わ + かる (wrong) → わかる (correct)
//
// Layer 1 Criteria:
//   ✅ Tokenization critical: Prevents incorrect splitting
//   ✅ High frequency: Common in everyday Japanese
//   ✅ Pure hiragana: No kanji forms
//
// Implementation Note:
//   Only BASE FORMS are registered here with proper ConjugationType.
//   Conjugated forms are AUTO-GENERATED by core_dict.cpp expandVerbEntry().
//   DO NOT manually add conjugated forms like できます, わかった, etc.
//
// NOT included here (use Layer 2 - data/core/dictionary.tsv):
//   ❌ Verbs with kanji (上げる, 下げる, 用いる, 伴う, etc.)
//   ❌ Na-adjectives (だめ, etc.)
// =============================================================================

#include <vector>

#include "dictionary/dictionary.h"

namespace suzume::dictionary::entries {

/**
 * @brief Get common hiragana verb entries for core dictionary
 *
 * These verbs are written in hiragana and start with characters that
 * could be mistaken for particles. They need dictionary entries to
 * prevent incorrect tokenization.
 *
 * Conjugated forms are auto-generated from base forms with ConjugationType.
 *
 * @return Vector of dictionary entries for common hiragana verbs
 */
std::vector<DictionaryEntry> getHiraganaVerbEntries();

}  // namespace suzume::dictionary::entries

#endif  // SUZUME_DICTIONARY_ENTRIES_HIRAGANA_VERBS_H_
