#ifndef SUZUME_DICTIONARY_ENTRIES_HIRAGANA_VERBS_H_
#define SUZUME_DICTIONARY_ENTRIES_HIRAGANA_VERBS_H_

// =============================================================================
// Layer 1: Hiragana Verbs (ひらがな動詞) - Tokenization Critical
// =============================================================================
// High-frequency verbs written ENTIRELY in hiragana that start with
// particle-like characters (で, も, わ, etc.). Without these entries,
// the analyzer incorrectly splits them as particle + verb fragment.
//
// Examples of bugs this fixes:
//   できる → で + きる (wrong) → できる (correct)
//   もらう → も + らう (wrong) → もらう (correct)
//   わかる → わ + かる (wrong) → わかる (correct)
//
// Layer 1 Criteria:
//   ✅ Tokenization critical: Prevents incorrect splitting
//   ✅ High frequency: Common in everyday Japanese
//   ✅ Pure hiragana: No kanji forms
//
// Implementation Note:
//   Only BASE FORMS are registered here with proper ConjugationType.
//   Conjugated forms are AUTO-GENERATED by core_dict.cpp expandVerbEntry().
//   DO NOT manually add conjugated forms like できます, わかった, etc.
//
// NOT included here (use Layer 2 - data/core/dictionary.tsv):
//   ❌ Verbs with kanji (上げる, 下げる, 用いる, 伴う, etc.)
//   ❌ Na-adjectives (だめ, etc.)
// =============================================================================

#include <vector>

#include "core/types.h"
#include "dictionary/dictionary.h"

namespace suzume::dictionary::entries {

/**
 * @brief Get common hiragana verb entries for core dictionary
 *
 * These verbs are written in hiragana and start with characters that
 * could be mistaken for particles. They need dictionary entries to
 * prevent incorrect tokenization.
 *
 * Conjugated forms are auto-generated from base forms with ConjugationType.
 *
 * @return Vector of dictionary entries for common hiragana verbs
 */
inline std::vector<DictionaryEntry> getHiraganaVerbEntries() {
  using POS = core::PartOfSpeech;
  using CT = ConjugationType;

  // Only BASE FORMS with proper ConjugationType
  // Conjugated forms are auto-generated by core_dict.cpp
  // Format: {surface, POS, cost, lemma, prefix, formal, low_info, conj, reading}
  return {
      // ========================================
      // Ichidan verbs (一段動詞)
      // ========================================
      // できる (to be able to) - starts with で
      {"できる", POS::Verb, 0.3F, "できる", false, false, false, CT::Ichidan, ""},

      // やめる (to stop/quit) - starts with や
      {"やめる", POS::Verb, 0.3F, "やめる", false, false, false, CT::Ichidan, ""},

      // はじめる (to begin) - starts with は
      {"はじめる", POS::Verb, 0.3F, "はじめる", false, false, false, CT::Ichidan, ""},

      // ========================================
      // Godan-Ka verbs (五段カ行)
      // ========================================
      // いただく (to receive, humble form of もらう) - starts with い
      // Without this entry, it's incorrectly parsed as i-adjective "いただい"
      {"いただく", POS::Verb, 0.3F, "いただく", false, false, false, CT::GodanKa, ""},

      // とく (contraction of ておく) - auxiliary verb for "do in advance"
      // Without this, "買っとく" incorrectly splits as 買+っとく(ADJ)
      {"とく", POS::Verb, 0.3F, "とく", false, false, true, CT::GodanKa, ""},
      // っとく form for verbs with っ-onbin (買っとく, やっとく, etc.)
      {"っとく", POS::Verb, -0.5F, "とく", false, false, true, CT::GodanKa, ""},

      // てく (contraction of ていく) - auxiliary verb for "go on doing"
      // Without this, "食べてく" incorrectly splits
      {"てく", POS::Verb, 0.3F, "てく", false, false, true, CT::GodanKa, ""},
      // っていく pattern
      {"ってく", POS::Verb, -0.5F, "てく", false, false, true, CT::GodanKa, ""},

      // ========================================
      // Godan-Ra verbs (五段ラ行)
      // ========================================
      // やる (to do) - starts with や, used in compound verbs (やり直す, etc.)
      {"やる", POS::Verb, 0.3F, "やる", false, false, false, CT::GodanRa, ""},

      // わかる (to understand) - starts with わ
      {"わかる", POS::Verb, 0.3F, "わかる", false, false, false, CT::GodanRa, ""},

      // なる (to become) - starts with な
      // Without this entry, "なりました" splits as "な" + "りました"
      {"なる", POS::Verb, 0.3F, "なる", false, false, false, CT::GodanRa, ""},

      // できあがる (to be completed) - compound hiragana verb
      {"できあがる", POS::Verb, 0.3F, "できあがる", false, false, false, CT::GodanRa, ""},

      // がんばる (to do one's best) - starts with が
      {"がんばる", POS::Verb, 0.3F, "がんばる", false, false, false, CT::GodanRa, ""},

      // ========================================
      // Godan-Wa verbs (五段ワ行)
      // ========================================
      // もらう (to receive) - starts with も
      {"もらう", POS::Verb, 0.3F, "もらう", false, false, false, CT::GodanWa, ""},

      // ========================================
      // Godan-Sa verbs (五段サ行)
      // ========================================
      // いたす (humble form of する)
      {"いたす", POS::Verb, 0.3F, "いたす", false, false, false, CT::GodanSa, ""},

      // ========================================
      // Suru verb (サ変動詞) - irregular
      // ========================================
      {"する", POS::Verb, 0.5F, "する", false, false, false, CT::Suru, ""},

      // ========================================
      // Kuru verb imperative only (カ変動詞命令形)
      // ========================================
      // こい (come!) - imperative of くる
      // Note: Full Kuru conjugation expansion is NOT done here because
      // forms like きた, きます conflict with てきた, できます patterns.
      // Only the imperative form is registered as it's unambiguous.
      {"こい", POS::Verb, 0.2F, "くる", false, false, false, CT::None, ""},

      // ========================================
      // Nouns derived from verbs (kept as-is, no expansion)
      // ========================================
      {"できあがり", POS::Noun, 0.3F, "できあがり", false, false, false, CT::None, ""},
  };
}

}  // namespace suzume::dictionary::entries

#endif  // SUZUME_DICTIONARY_ENTRIES_HIRAGANA_VERBS_H_
