#ifndef SUZUME_ANALYSIS_JOIN_COMPOUND_VERB_INTERNAL_H_
#define SUZUME_ANALYSIS_JOIN_COMPOUND_VERB_INTERNAL_H_

#include <cstddef>
#include <string>

#include "bigram_table.h"
#include "candidate_constants.h"
#include "core/debug.h"
#include "core/utf8_constants.h"
#include "grammar/char_patterns.h"
#include "grammar/inflection.h"
#include "join_candidates.h"
#include "normalize/char_type.h"
#include "normalize/exceptions.h"
#include "normalize/utf8.h"
#include "tokenizer_utils.h"
#include "verb_candidates_helpers.h"

namespace suzume::analysis::compound_verb_detail {

using CharType = normalize::CharType;

// V2 Subsidiary verbs for compound verb joining
// Verb type determines how to generate renyokei from base form
enum class V2VerbType : uint8_t {
  Godan,    // 五段: 込む→込み, 返す→返し (replace ending with i-row)
  Ichidan,  // 一段: 続ける→続け, 上げる→上げ (drop る)
};

// The compound inherits V2's inflection class. Retaining this on generated
// edges prevents later lemmatization from treating a GodanSa compound such as
// 見直す as the classical suru form 見直する.
dictionary::ConjugationType compoundConjugationType(V2VerbType verb_type, std::string_view base_ending);

struct SubsidiaryVerb {
  const char* surface;      // Kanji form (or hiragana if no kanji)
  const char* reading;      // Hiragana reading (nullptr if same as surface)
  const char* base_ending;  // Base form ending for verb type detection
  V2VerbType verb_type;     // Determines renyokei generation
  // Sahen continuatives normally join their lexical V2 (し続ける).  V2s
  // whose preceding し remains an independent search unit opt out here.
  bool joins_suru{true};
  // Most entries also join ordinary V1 continuatives. A closed auxiliary can
  // be restricted to the Sahen path while remaining separate after other V1s.
  bool joins_general{true};
  // Some kanji V2s have a hiragana reading that is also a productive
  // auxiliary contraction. Keep those entries available only in kanji form.
  bool joins_reading{true};
  // A reading-only V2 is available for kana spelling but must not match the
  // corresponding kanji spelling. This keeps orthographically distinct
  // compound boundaries from sharing a lexical entry by accident.
  bool joins_surface{true};
};

// The selected V2 entry and the evidence collected while matching it. Match
// policy produces this value; the emitter consumes it without re-searching the
// closed lexicon.
struct CompoundVerbMatch {
  size_t matched_len = 0;
  std::string compound_base;
  std::string compound_source_base;
  bool is_renyokei = false;
  bool renyokei_form = false;
  bool is_mizenkei = false;
  bool is_volitional = false;
  bool is_kateikei = false;
  bool is_potential = false;
  bool includes_aux = false;
  bool matched_via_reading = false;
  float confidence = 0.0F;
  const SubsidiaryVerb* v2_verb = nullptr;
  bool v1_dict_verified = false;
  bool v1_embedded_verified = false;
  bool v1_ichidan_inflection = false;
  bool v1_bare_ichidan = false;
  bool v1_godan_inflection = false;
};

// Inputs to V1 verification are grouped separately from V2 matching so the
// language-specific fallback policy can live in its own translation unit.
struct CompoundV1VerificationRequest {
  std::string_view text;
  const std::vector<char32_t>& codepoints;
  const ByteOffsets& byte_offsets;
  size_t start_pos;
  size_t kanji_end;
  size_t v2_start;
  size_t start_byte;
  size_t v2_start_byte;
  char32_t base_ending;
  bool is_sokuonbin;
  bool is_ichidan;
  bool has_kanji_v2_after_bare_ichidan;
  bool dict_compound_v1;
  bool hiragana_v1;
  bool allow_closed_onbin_v1;
  std::string_view dict_compound_v1_lemma;
  const dictionary::DictionaryManager& dict_manager;
  const grammar::Inflection& inflection;
};

// Evidence generated by V1 verification. The match policy uses these fields
// without re-evaluating dictionary or inflection fallbacks.
struct CompoundV1Verification {
  bool verified = false;
  bool dict_verified = false;
  bool embedded_verified = false;
  bool ichidan_inflection = false;
  bool godan_inflection = false;
};

// The V2 allowlist has one owner in join_compound_verb_lexicon.cpp.  Keep
// iteration range-based at every consumer so matching order remains the table
// order without exposing the static storage in this header.
struct SubsidiaryVerbRange {
  const SubsidiaryVerb* first;
  const SubsidiaryVerb* last;

  const SubsidiaryVerb* begin() const { return first; }
  const SubsidiaryVerb* end() const { return last; }
};

inline constexpr size_t kSubsidiaryVerbCount = 176;
extern const SubsidiaryVerb kSubsidiaryVerbs[kSubsidiaryVerbCount];

inline SubsidiaryVerbRange subsidiaryVerbs() {
  return {kSubsidiaryVerbs, kSubsidiaryVerbs + kSubsidiaryVerbCount};
}

// Closed auxiliary classes that attach to a verb mizenkei. Keep matcher and
// emitter on one predicate so classical negative variants cannot drift. The
// classical conjectural む/ん and its negative じ select the same cell as the
// negatives do, so a compound stem keeps its boundary in front of them too
// (見送ら|む, not 見|送ら|む). `following` is the codepoint after the starter, or
// zero at the end of the input.
inline bool isMizenkeiAuxiliaryStarter(char32_t codepoint, char32_t following) {
  // ん is also the hatsuonbin of the ma/ba/na rows, and there it carries the
  // tense marker that no negative takes: 折りたたん+で is the te-form of
  // 折りたたむ, not its irrealis before a contracted negative.
  if (codepoint == U'ん') {
    return following != U'で' && following != U'だ';
  }
  // The literary passive takes the same cell as the modern れる and spells its
  // adnominal るる and its realis るれ. Its bare terminal る is left out: one
  // mora is the base ending of half the verbs, so a compound V2 would lose its
  // own paradigm to it (振り返る is not 振り+返+る).
  if (codepoint == U'る') {
    return following == U'る' || following == U'れ';
  }
  return codepoint == U'れ' || codepoint == U'せ' || codepoint == U'な' || codepoint == U'ず' || codepoint == U'ぬ' ||
         codepoint == U'ね' || codepoint == U'む' || codepoint == U'じ';
}

// Emits the continuative subsidiary behind a voice auxiliary (the 続ける of
// れ続ける and its inflections) and returns true when that grammar-owned path
// consumes the candidate span.
bool addPassiveContinuativeTailCandidates(core::Lattice& lattice, const std::vector<char32_t>& codepoints,
                                          size_t kanji_end);

// Resolves V2 forms, verifies the corresponding V1, and returns the highest-priority
// match. The caller retains V2 boundary discovery and emits the selected edge separately.
CompoundVerbMatch findCompoundVerbMatch(
    std::string_view text, const std::vector<char32_t>& codepoints, const ByteOffsets& byte_offsets, size_t start_pos,
    const std::vector<normalize::CharType>& char_types, size_t kanji_end, size_t v2_start, char32_t base_ending,
    bool is_sokuonbin, bool is_ichidan, bool has_kanji_v2_after_bare_ichidan, bool dict_compound_v1,
    std::string_view dict_compound_v1_lemma, const dictionary::DictionaryManager& dict_manager,
    const grammar::Inflection& inflection, bool hiragana_v1 = false, bool allow_closed_onbin_v1 = false);

// Reconstructs and verifies V1 before the V2 matching policy compares it with
// competing subsidiary-verb matches.
CompoundV1Verification verifyCompoundVerbV1(const CompoundV1VerificationRequest& request);

void emitCompoundVerbCandidates(core::Lattice& lattice, std::string_view text, const std::vector<char32_t>& codepoints,
                                const ByteOffsets& byte_offsets, size_t start_pos, size_t v2_start,
                                const CompoundVerbMatch& match, const dictionary::DictionaryManager& dict_manager,
                                const Scorer& scorer);

// True when the following dictionary context forces the preceding renyokei
// compound to act as a deverbal noun rather than a predicate.
bool beginsNominalForcingParticle(const std::vector<char32_t>& codepoints, size_t pos,
                                  const dictionary::DictionaryManager& dict_manager);

// Sokuonbin-compatible godan verb endings (く, つ, う, る)
// Used to try all possible base forms when analyzing っ-onbin compound verbs
inline constexpr char32_t kSokuonbinEndings[] = {U'く', U'つ', U'う', U'る'};

// Generate renyokei surface from base form
// Godan: replace ending with i-row (込む→込み, 返す→返し)
// Ichidan: drop る (続ける→続け)
std::string generateRenyokei(std::string_view surface, std::string_view reading, V2VerbType verb_type);

// Generate mizenkei surface from base form
// Godan: replace ending with a-row (込む→込ま, 返す→返さ)
// Ichidan: drop る (続ける→続け, same as renyokei for ichidan)
std::string generateMizenkei(std::string_view surface, std::string_view reading, V2VerbType verb_type);

// Generate the Godan o-row stem selected by the volitional auxiliary う.
std::string generateVolitionalStem(std::string_view surface, std::string_view reading, V2VerbType verb_type);

// Generate kateikei surface from base form
// Godan: replace ending with e-row (返す→返せ)
// Ichidan: replace る with れ (続ける→続けれ)
std::string generateKateikei(std::string_view surface, std::string_view reading, V2VerbType verb_type);

// Generate a Godan potential form (戻す→戻せる) from the dictionary form.
// The V2 allowlist controls which lexical verbs participate; this merely shares
// their ordinary Godan conjugation across all of those entries.
std::string generateGodanPotential(std::string_view surface, std::string_view reading, V2VerbType verb_type);

// Te-form euphonic form type for Godan verbs
enum class TeFormType : uint8_t {
  Ionbin,      // イ音便 (書く→書い, 泳ぐ→泳い) + て/で
  Sokuonbin,   // 促音便 (待つ→待っ, 買う→買っ, 帰る→帰っ) + て
  Hatsuonbin,  // 撥音便 (読む→読ん, 飛ぶ→飛ん, 死ぬ→死ん) + で
  Renyokei,    // 連用形 (話す→話し) + て
  Ichidan,     // 一段 (食べる→食べ) + て
};

// Determine te-form type and suffix from verb ending
TeFormType getTeFormType(std::string_view base_ending);

// Generate te-form euphonic stem (before て/で)
// Returns: stem and whether it uses で (vs て)
std::pair<std::string, bool> generateTeFormStem(std::string_view surface, std::string_view reading,
                                                V2VerbType verb_type, std::string_view base_ending);

// Generate kanji renyokei from kanji surface
std::string generateKanjiRenyokei(std::string_view kanji_surface, std::string_view reading, V2VerbType verb_type);

// Map a Godan i-row 連用形 codepoint (き, ぎ, し, ...) to its dictionary-form
// codepoint (く, ぐ, す, ...); returns 0 when the char is not a Godan renyokei
// ending. Backed by the shared Conjugation-derived table in grammar so the
// い段→終止形 mapping lives in exactly one place.
char32_t godanRenyokeiBaseCp(char32_t renyokei_cp);

// Cost bonuses imported from candidate_constants.h:
// candidate::kCompoundVerbBonus, candidate::kVerifiedV1Bonus

}  // namespace suzume::analysis::compound_verb_detail

#endif  // SUZUME_ANALYSIS_JOIN_COMPOUND_VERB_INTERNAL_H_
